//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenShoe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public long ProductID { get; set; }
        public long OrderID { get; set; }
        public long SizeID { get; set; }
        public long ColorID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Order Order { get; set; }
    }
}
