//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenShoe.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long ProductID { get; set; }
        public string Name { get; set; }
        public string MetaTitle { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> PromotionPrice { get; set; }
        public string Detail { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public Nullable<long> ProductCategoryID { get; set; }
        public Nullable<int> Warranty { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> New { get; set; }
        public string Image { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ProductCategory ProductCategory { get; set; }
    }
}
